### ISSUE TITLE
Support for Interpolations 0.14

### ISSUE THREAD

**Issue by ThummeTo** [m3g/EasyFit.jl#6]
Current Julia versions (1.8) often build dependency trees requiring `Interpolations.jl v0.14` and newer.
Would be nice to add this and trigger a release. The commands that I use (like `movavg`) seem wo work also with the newer `Interpolations.jl` version, however I did not check every function.

PS: If you're lazy I opened a PR :-)

**Comment by lmiq** [comment]
Done.
